services:
  app:
    build:
      context: .
    container_name: saude_api
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:hfoPa6PUmnCBXdCJ07pqalPQIlWLcsrZIckr+FPe9i0=
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: saude-db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: saude_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saude-db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
